repos:
-   repo: https://github.com/ambv/black
    rev: '24.4.2'
    hooks:
    - id: black
      language_version: python3.12
      stages: [commit]
-   repo: https://github.com/pycqa/flake8
    rev: '7.1.0'
    hooks:
    - id: flake8
      stages: [commit]
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      language: system
      entry: pytest -v -s
      always_run: true
      pass_filenames: false
      stages: [commit]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'venv/bin/pip3 freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]